# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

setupcontainer: &setupcontainer
  docker:
    - image: circleci/node:6-browsers
  working_directory: ~/repo

steps: &steps
  - checkout
  - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-
  - run: yarn install --frozen-lockfile --non-interactive
  - save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}
  - run: node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

version: 2
jobs:
  lts2.18:
    <<: *setupcontainer
    environment:
      EMBER_TRY_SCENARIO: ember-lts-2.18
    steps: *steps

  lts.3.4:
    <<: *setupcontainer
    environment:
      EMBER_TRY_SCENARIO: ember-lts-3.4
    steps: *steps

  release:
    <<: *setupcontainer
    environment:
      EMBER_TRY_SCENARIO: ember-release
    steps: *steps

  beta:
    <<: *setupcontainer
    environment:
      EMBER_TRY_SCENARIO: ember-beta
    steps: *steps

  canary:
    <<: *setupcontainer
    environment:
      EMBER_TRY_SCENARIO: ember-canary
    steps: *steps

  jquery:
    <<: *setupcontainer
    environment:
      EMBER_TRY_SCENARIO: ember-default-with-jquery
    steps: *steps

  linthbs:
    <<: *setupcontainer
    environment:
      EMBER_TRY_SCENARIO: ember-lts-2.18
    steps: *steps